
- name: Disable logstash at boot and stopped service
  systemd:
    name: logstash.service
    state: stopped
    enabled: false
    daemon_reload: yes
  ignore_errors: True
  tags: logstash



- name: Remove Logstash service into systemd and reloading daemon
  file: 
    path: /etc/systemd/system/logstash.service 
    state: absent
  tags: logstash



- name: Remove Logstash
  yum:
    name: logstash
    state: absent
  tags: logstash


- name: Remove logstash-6.x repository
  file: 
    path: /etc/yum.repos.d/logstash.repo 
    state: absent
  tags: logstash


